### ISSUE TITLE
Invalid needs-restarting option

### ISSUE THREAD

**Issue by broferek** [angrox/ansible-centos-updates#1]
Hi

I'm running a EL 6.9 and have an issue with the task "needs-restarting -r".

-r is an invalid option for EL6

I think we need to differentiate the tasks between EL6 and EL7.

Do you want me to provide a pull request fixing this?

Thanks

Ludo

**Comment by angrox** [comment]
Hi! Thanks to look into it. If you have the fix ready it would be awesome if you could provide it!

**Comment by broferek** [comment]
I'll send a pull request today with what I came to.

**Comment by broferek** [comment]
Here we go : https://github.com/angrox/ansible-centos-updates/pull/2

**Comment by broferek** [comment]
Hi,

have you reviewed the pull request?

Thanks,

Ludo

**Comment by angrox** [comment]
Thanks for the pull request - it is merged now!
